secrets: secrets.yml

templates:
  download:
    seen: local
    verify_ssl_certificates: no
    priority: 2
    transmission:
      host: localhost
      port: 9091
      username: '{{ secrets.transmission.user }}'
      password: '{{ secrets.transmission.password }}'
      addpaused: no

tasks:
  #queue movies from my trakt watchlist
  movie-queue:
    trakt_list:
      username: '{{secrets.trakt.user}}'
      type: movies
      list: watchlist
    accept_all: yes
    trakt_remove: 
      username: '{{secrets.trakt.user}}'
      account: '{{secrets.trakt.user}}'
      list: watchlist
    movie_queue:
      action: add
      quality: webdl+ 720p+
    priority: 1
    seen: local

  # download shows from torrent rss feeds
  download-shows:
    template: [download]
    ### Main RSS feed to keep up (showrss.info)
    rss: http://showrss.info/rss.php?user_id={{ secrets.showrss.user_id }}&hd=null&proper=null

    all_series: yes
    accept_all: yes
    exists_series:
      - /media/transmission/downloading
      - /media/transmission/tv
      - /media/transmission/downloads
      - /media/public/TV/{{series_name}}
    priority: 2
    transmission:
      path: /media/transmission/tv

  download-movies:
    template: [download]
    discover:
      what:
        - emit_movie_queue: yes
      from:
        #- isohunt: movies
        - rarbg:
        #     #category:
        #     #  - x264 720p
        #     #  - x264 1080p
             sorted_by: seeders
             use_tvdb: false

    movie_queue: accept
    #disable: [remember_rejected, retry_failed]
    #seen_movies: strict
    regexp:
      reject:
        - \b3D\b: {from: title}
    priority: 2
    transmission:
      path: /media/transmission/movies

  subtitles:
    filesystem:
      path: 
        - /media/transmission/tv
        - /media/transmission/movies
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    regexp:
      reject:
        - \bsample\b: {from: title}
    accept_all: yes
    no_entries_ok: yes
    seen: local
    #disable: [retry_failed]
    subliminal:
      languages:
        - eng
      exact_match: yes
    priority: 3

  sort-shows:
    filesystem:
      path: /media/transmission/tv
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    regexp:
      reject:
        - \bsample\b: {from: title}
 
    series:
      settings:
        numeric:
          ep_regexp:
            - (\d\d)(\d\d)
            - (\d)(\d\d)
          parse_only: yes
        sequence:
          identified_by: sequence
      numeric:
        - The Big Bang Theory
        - Better Call Saul
        - Criminal Minds
        - The Simpsons
        - American Dad
        - Family Guy
        - Mr Robot
        - Masters of Sex
        - Greys Anatomy

    accept_all: yes
    no_entries_ok: yes
    seen: local
    priority: 4
    thetvdb_lookup: yes
    require_field: [series_name, series_season]
    disable: [retry_failed]
    all_series:
      # for some reason all_series rejects all episodes here, even with seen: local, so parse_only must be added
      parse_only: yes
    copy:
      to: /media/public/TV/{{ series_name }}/Season {{ series_season }}
      # save the file as "Series Name - SxxEyy - Episode Name.ext"
      filename: '{{ tvdb_series_name }} - {{ series_id }} - {{ tvdb_ep_name|default("Unknown") }}{{ location | pathext }}'
      along:
        - srt
        - en.srt
        - sub
        - idx
        - nfo

  sort-movies:
    filesystem:
      path: /media/transmission/movies
      recursive: yes
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    no_entries_ok: yes
    disable: [retry_failed]
    tmdb_lookup: yes
    imdb_lookup: yes
    seen: local
    priority: 4
    regexp:
      reject:
        - \bsample\b: {from: title}
    require_field: [movie_name, movie_year]
    copy:
      to: /media/public/Movies/{{ movie_name }} ({{ movie_year }})
      filename: '{{ movie_name }} ({{ movie_year }}) - {{ quality }}{{ location | pathext }}'

  clean_transmission:
    manual: yes
    disable: [details]
    clean_transmission:
      host: localhost
      port: 9091
      username: '{{ secrets.transmission.user }}'
      password: '{{ secrets.transmission.password }}'
      finished_for: 2 hours
      min_ratio: 0.9
      delete_files: yes

schedules:
  - tasks: 
      - movie-queue
      - download-shows
      - download-movies
      - subtitles
      - sort-shows
      - sort-movies
    interval:
      hours: 2
